import { Order, OrderResponse, Designer, DesignerProject, Manufacturer, ManufacturerProduct, StandardDocument } from './types';

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order1',
    customerId: 'cust1',
    customerName: 'ООО «СтройИнвест»',
    title: 'Проектирование жилого комплекса «Парк Резиденс»',
    description: 'Требуется разработка проектной документации стадии П для жилого комплекса бизнес-класса. 3 секции, 18 этажей, подземная автостоянка. Общая площадь 45 000 м².',
    objectType: 'commercial',
    region: 'Москва',
    scale: 'team',
    stage: 'P',
    sections: ['АР', 'КР', 'ЭОМ', 'ВК', 'ОВиК', 'ПОС', 'ПБ', 'СМ'],
    specialists: ['Архитектор', 'ГАП', 'Конструктор', 'Инженер-электрик', 'Инженер-сантехник'],
    budget: '12 000 000 ₽',
    deadline: '2026-09-01',
    status: 'published',
    responsesCount: 5,
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'order2',
    customerId: 'cust2',
    customerName: 'ИП Козлов А.В.',
    title: 'Рабочая документация коттеджа 350 м²',
    description: 'Нужна РД для двухэтажного коттеджа с цокольным этажом. Кирпич, монолитный фундамент. Участок 15 соток в Подмосковье.',
    objectType: 'private',
    region: 'Московская область',
    scale: 'single',
    stage: 'RD',
    sections: ['АР', 'КР', 'ВК', 'ОВ', 'ЭО'],
    specialists: ['Архитектор', 'Конструктор', 'Инженер-сантехник'],
    budget: '800 000 ₽',
    deadline: '2026-06-15',
    status: 'published',
    responsesCount: 12,
    createdAt: '2026-03-14T15:30:00Z',
  },
  {
    id: 'order3',
    customerId: 'cust3',
    customerName: 'АО «НефтеХимПром»',
    title: 'Проект модернизации установки ЭЛОУ-АВТ',
    description: 'Проектная документация на модернизацию атмосферно-вакуумной установки. Производительность 6 млн т/год. Требуется опыт работы с объектами нефтепереработки.',
    objectType: 'industrial',
    region: 'Республика Татарстан',
    scale: 'team',
    stage: 'P',
    sections: ['ТХ', 'КР', 'ЭОМ', 'АК', 'ПБ', 'ООС', 'СМ'],
    specialists: ['Технолог', 'Конструктор', 'Инженер-электрик', 'Специалист по ПБ'],
    budget: '28 000 000 ₽',
    deadline: '2026-12-01',
    status: 'published',
    responsesCount: 3,
    createdAt: '2026-03-13T09:00:00Z',
  },
  {
    id: 'order4',
    customerId: 'cust1',
    customerName: 'ООО «СтройИнвест»',
    title: 'Водоснабжение микрорайона «Солнечный»',
    description: 'Проектирование наружных сетей водоснабжения и канализации для нового микрорайона. Протяжённость сетей — 4.2 км.',
    objectType: 'linear',
    region: 'Краснодарский край',
    scale: 'team',
    stage: 'P',
    sections: ['ПЗ', 'ТКР', 'ПОС', 'ООС', 'СМ'],
    specialists: ['Инженер наружных сетей (ВС)', 'Инженер наружных сетей (КН)'],
    budget: '5 500 000 ₽',
    deadline: '2026-08-01',
    status: 'in_progress',
    responsesCount: 7,
    createdAt: '2026-03-10T12:00:00Z',
  },
  {
    id: 'order5',
    customerId: 'cust4',
    customerName: 'МКУ «Управление капстроительства»',
    title: 'Проект школы на 1100 мест',
    description: 'Требуется полный комплект ПД для общеобразовательной школы. 4 этажа, спортзал, бассейн, актовый зал. Площадь участка 2.5 га.',
    objectType: 'buildings',
    region: 'Новосибирская область',
    scale: 'team',
    stage: 'P',
    sections: ['ПЗ', 'ПЗУ', 'АР', 'КР', 'ЭОМ', 'ВК', 'ОВиК', 'СС', 'ПОС', 'ООС', 'ПБ', 'ОДИ', 'СМ', 'ГОЧС'],
    specialists: ['Генпроектировщик', 'Архитектор', 'ГАП', 'Конструктор'],
    budget: 'Ждём предложений',
    deadline: '2026-11-30',
    status: 'published',
    responsesCount: 8,
    createdAt: '2026-03-12T08:00:00Z',
  },
  {
    id: 'order6',
    customerId: 'cust5',
    customerName: 'ООО «АвтоТранс»',
    title: 'Реконструкция складского комплекса',
    description: 'Реконструкция складского комплекса класса А. Общая площадь 12 000 м². Замена кровли, утепление, модернизация инженерных систем.',
    objectType: 'commercial',
    region: 'Свердловская область',
    scale: 'team',
    stage: 'RD',
    sections: ['АР', 'КР', 'ЭО', 'ОВ', 'ВК', 'ПОС'],
    specialists: ['Архитектор', 'Конструктор', 'Инженер ОВиК'],
    budget: '3 200 000 ₽',
    deadline: '2026-07-15',
    status: 'completed',
    responsesCount: 9,
    createdAt: '2026-02-20T10:00:00Z',
  },
];

export const MOCK_RESPONSES: OrderResponse[] = [
  {
    id: 'resp1',
    orderId: 'order1',
    designerId: 'des1',
    designerName: 'Архитектурное бюро «ПРОЕКТ.А»',
    designerCompany: 'ООО «ПРОЕКТ.А»',
    message: 'Имеем опыт проектирования ЖК бизнес-класса. Выполнили более 15 аналогичных проектов. Готовы приступить в течение 2 недель.',
    proposedBudget: '10 800 000 ₽',
    proposedDeadline: '2026-08-15',
    createdAt: '2026-03-15T14:00:00Z',
  },
  {
    id: 'resp2',
    orderId: 'order1',
    designerId: 'des2',
    designerName: 'ГК «ИнжПроектСервис»',
    designerCompany: 'ООО «ИнжПроектСервис»',
    message: 'Специализируемся на комплексном проектировании. В штате 50+ специалистов. СРО уровень 3.',
    proposedBudget: '11 500 000 ₽',
    proposedDeadline: '2026-09-01',
    createdAt: '2026-03-15T16:30:00Z',
  },
  {
    id: 'resp3',
    orderId: 'order2',
    designerId: 'des3',
    designerName: 'Иванов Сергей Петрович',
    message: 'Проектирую частные дома 8 лет. Портфолио: 40+ реализованных проектов. Работаю в Revit.',
    proposedBudget: '650 000 ₽',
    proposedDeadline: '2026-05-30',
    createdAt: '2026-03-14T18:00:00Z',
  },
  {
    id: 'resp4',
    orderId: 'order5',
    designerId: 'des1',
    designerName: 'Архитектурное бюро «ПРОЕКТ.А»',
    designerCompany: 'ООО «ПРОЕКТ.А»',
    message: 'Имеем опыт проектирования образовательных учреждений. Выполнили 5 школ и 3 детских сада.',
    proposedBudget: '18 000 000 ₽',
    proposedDeadline: '2026-11-01',
    createdAt: '2026-03-12T14:00:00Z',
  },
];

// === Проектировщики ===
export const MOCK_DESIGNERS: Designer[] = [
  {
    id: 'dsn1',
    name: 'Олег Соколов',
    type: 'person',
    sections: ['АР', 'АР'],
    city: 'Санкт-Петербург',
    sroNumber: 'СРО ООО «Альфа-Проект»',
    rating: 4.6,
    reviewsLabel: 'Рейтинг',
    projectsCount: 198,
    yearsExperience: 12,
    phone: '+7 912 345-67-89',
    email: 'sokolov@proekt.ru',
    achievements: ['Заявки', 'Звонки'],
    description: 'Архитектор с опытом проектирования жилых комплексов. Работает в AutoCAD, Revit и ArchiCAD.',
  },
  {
    id: 'dsn2',
    name: 'Вадим Петров',
    type: 'person',
    sections: ['КР', 'АР'],
    city: 'Санкт-Петербург',
    region: 'Санкт-Петербург, ПО, МСК',
    sroNumber: 'СРО НБПI-04-032',
    rating: 4.8,
    reviewsLabel: 'Рейтинг',
    projectsCount: 21,
    yearsExperience: 6,
    phone: '+7 987 125-45-67',
    email: 'petrov@design.ru',
    achievements: ['С 2020 года в проектировании', '3 года стажа в проектировании', 'Первые места в конкурсах'],
  },
  {
    id: 'dsn3',
    name: 'ООО «ПроектСити»',
    type: 'company',
    sections: ['КР'],
    city: 'Москва',
    sroNumber: 'СРО ДОМФ-01-134',
    rating: 4.7,
    reviewsLabel: 'Рейтинг',
    projectsCount: 86,
    yearsExperience: 15,
    phone: '+7 495 123-45-67',
    email: 'info@proektcity.ru',
    achievements: ['Заявки', 'Звонки'],
  },
  {
    id: 'dsn4',
    name: 'Андрей Смирнов',
    type: 'person',
    sections: ['КР'],
    city: 'Воронеж',
    sroNumber: 'СРО ПТЗ-05-456',
    rating: 4.5,
    reviewsLabel: 'Рейтинг',
    projectsCount: 48,
    yearsExperience: 8,
    phone: '+7 920 111-22-33',
    email: 'smirnov@arch.ru',
    achievements: ['АР', 'Звонки'],
  },
  {
    id: 'dsn5',
    name: 'АрхПроект Строй',
    type: 'company',
    sections: ['КР', 'КР'],
    city: 'Санкт-Петербург',
    sroNumber: 'СРО ППЦ-02-467',
    rating: 4.7,
    reviewsLabel: 'Рейтинг',
    projectsCount: 66,
    yearsExperience: 10,
    phone: '+7 812 222-33-44',
    email: 'info@archproekt.ru',
    achievements: ['АР', 'Звонки'],
  },
  {
    id: 'dsn6',
    name: 'Елена Волкова',
    type: 'person',
    sections: ['ЭОМ', 'ВК'],
    city: 'Москва',
    sroNumber: 'СРО ИНЖ-07-891',
    rating: 4.9,
    reviewsLabel: 'Рейтинг',
    projectsCount: 74,
    yearsExperience: 14,
    phone: '+7 926 555-66-77',
    email: 'volkova@eng.ru',
    achievements: ['Заявки', 'Звонки'],
    description: 'Инженер электрик-сетей. Более 70 реализованных проектов.',
  },
  {
    id: 'dsn7',
    name: 'ООО «СПД»',
    type: 'company',
    sections: ['ТУС'],
    city: 'Москва',
    sroNumber: 'СРО СПП-77-187',
    rating: 4.5,
    reviewsLabel: 'Рейтинг',
    projectsCount: 188,
    yearsExperience: 20,
    phone: '+7 495 999-88-77',
    email: 'info@spd.ru',
    achievements: ['ТЕВ', 'Звонки'],
  },
  {
    id: 'dsn8',
    name: 'Дмитрий Орлов',
    type: 'person',
    sections: ['ОВиК', 'ГС'],
    city: 'Краснодар',
    sroNumber: 'СРО КРД-12-345',
    rating: 4.3,
    reviewsLabel: 'Рейтинг',
    projectsCount: 35,
    yearsExperience: 7,
    phone: '+7 918 444-55-66',
    email: 'orlov@vent.ru',
    achievements: ['Заявки', 'Звонки'],
  },
];

// === Последние проекты ===
export const MOCK_PROJECTS: DesignerProject[] = [
  { id: 'prj1', title: 'ЖК Ренессанс', location: 'Санкт-Петербург', projectsCount: 67 },
  { id: 'prj2', title: 'МФК Старый город', location: 'Кол инженер каналы России', projectsCount: 17 },
  { id: 'prj3', title: 'Торговый центр', location: 'Москва', projectsCount: 42 },
  { id: 'prj4', title: 'Присанких центр', location: 'Новосибирск', projectsCount: 23 },
];

// === Производители и Решения ===
export const MOCK_MANUFACTURERS: Manufacturer[] = [
  {
    id: 'mfg1',
    name: 'ООО «ТехФасад»',
    description: 'Производитель фасадных систем и узлов для жилых и коммерческих зданий',
    tags: ['BIM', 'Узлы', 'СП / ГОСТ', 'АР / КР'],
    rating: 4.8,
    projectsCount: 120,
    deliveryRegion: 'РФ / СНГ',
    website: 'www.techfasad.ru',
    email: 'info@techfasad.ru',
    phone: '+7 495 125-45-67',
  },
  {
    id: 'mfg2',
    name: 'Завод ЖБИ «ЗапСибСтрой»',
    description: 'Производство ЖБИ изделий для промышленного и гражданского строительства',
    tags: ['КР', 'Нормативы', 'Промышленность'],
    rating: 4.9,
    projectsCount: 87,
    deliveryRegion: 'РФ / СНГ',
  },
  {
    id: 'mfg3',
    name: 'Завод ЖБИ «ЗапСибСтрой»',
    description: 'Производство ЖБИ изделий для промышленного и гражданского строительства',
    tags: ['КР', 'Нормативы', 'Промышленность'],
    rating: 4.9,
    projectsCount: 87,
    deliveryRegion: 'РФ / СНГ',
  },
  {
    id: 'mfg4',
    name: 'АО «ПрофМет»',
    description: 'Производитель металлических конструкций, поставщик для кровельных систем',
    tags: ['КР', 'Металл', 'ГОСТ'],
    rating: 4.6,
    projectsCount: 65,
    deliveryRegion: 'РФ',
  },
];

export const MOCK_MANUFACTURER_PRODUCTS: ManufacturerProduct[] = [
  {
    id: 'prod1',
    name: 'Фасадная система F-300',
    subtitle: 'Навес на фасад',
    tags: ['BIM', 'Узлы', 'FC', 'Сертификаты'],
    spec: 'СП 60, ГОСТ-31231',
    certCount: 18,
  },
  {
    id: 'prod2',
    name: 'Узел крепления UF-12',
    subtitle: 'Узел фасада',
    tags: ['BIM', 'Узлы', 'ГОСТ', 'КР'],
    spec: 'ФС ГОСТ-31231',
    certCount: 68,
  },
];

// === Нормативные документы ===
export const MOCK_STANDARDS: StandardDocument[] = [
  { id: 'std1', code: 'ГОСТ 21.602-2016', title: 'Проектная документация', type: 'ГОСТ', section: 'Общие положения', year: 2023, status: 'Актуален', updatedYear: 2023, isFeatured: true },
  { id: 'std2', code: 'ГОСТ 34.201-2021', title: 'АСУ ТП', type: 'ГОСТ', section: 'АСУ ТП', year: 2024, status: 'Актуален', updatedYear: 2024, isFeatured: true },
  { id: 'std3', code: 'ГОСТ 21.412-2022', title: 'Автоматизация', type: 'ГОСТ', section: 'Автоматизация', year: 2024, status: 'Актуален', updatedYear: 2024, isFeatured: true },
  { id: 'std4', code: 'ГОСТ 21.1101', title: 'Основные требования к проектной документации', type: 'ГОСТ', section: 'Общие положения', year: 2022, status: 'Актуален' },
  { id: 'std5', code: 'СП 60.13330', title: 'Отопление, вентиляция и кондиционирование', type: 'СП', section: 'Отопление', year: 2023, status: 'Актуален' },
  { id: 'std6', code: 'СНиП 2.04', title: 'Водоснабжение наружное', type: 'СНиП', section: 'Водоснабжение', year: 2001, status: 'Устарел' },
  { id: 'std7', code: 'ISO 9001-2015', title: 'Системы менеджмента качества', type: 'ISO', section: 'Системы менеджмента', year: 2015, status: 'Актуален' },
  { id: 'std8', code: 'ГОСТ-66-3020', title: 'Нефть и газ', type: 'ГОСТ', section: 'Нефть и газ', year: 2030, status: 'Актуален' },
  { id: 'std9', code: 'ГОСТ-62.3341', title: 'Теплоизоляция', type: 'ГОСТ', section: 'Тепловая изоляция', year: 2020, status: 'Актуален' },
];

// Свежие изменения за неделю
export const MOCK_RECENT_CHANGES = [
  { code: 'ГОСТ 2104-2024', spec: 'СП ГОСТ-2.2036', count: 925, status: 'Актуален' as const },
  { code: 'СП 301.3330-2023', spec: 'СП ГОСТ-8.2019', count: 924, status: 'Ситуацион.' as const },
  { code: 'ГОСТ 13109-2024', spec: 'СП ГОСТ-8.24036', count: 925, status: 'Ситуацион.' as const },
];

// Избранное проектировщика
export const MOCK_FAVORITES = [
  { code: 'ГОСТ 28.13330', spec: 'СП МОС-01.2021' },
  { code: 'СНиП 23.101', spec: 'СП МОС-01.2004' },
  { code: 'ГОСТ 32800-2013', spec: 'СП МОС-01.2014' },
];
